//TYPES DE USUARIOS
export const ADD_NEW_USER = 'ADD_NEW_USER';
export const GET_USER = 'GET_USER';
export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const CLOSE_SESSION = 'CLOSE_SESSION';
 
//TYPES DE RESTAURANTES
export const ADD_NEW_RESTAURANT = 'ADD_NEW_RESTAURANT';
export const GET_RESTAURANTS = 'GET_RESTAURANTS';
export const RESTAURANT_USED = 'RESTAURANT_USED';
export const RESTAURANT_USED_NULL = 'RESTAURANT_USED_NULL';
export const UPDATE_RESTAURANT = 'UPDATE_RESTAURANT';
export const DELETE_RESTAURANT = 'DELETE_RESTAURANT';
export const FORM_TRUE = 'FORM_TRUE';
export const FORM_NULL = 'FORM_NULL';

//TYPES DE SUCURSALES
export const ADD_NEW_BRANCH = 'ADD_NEW_BRANCH';
export const GET_BRANCH = 'GET_BRANCH';
export const BRANCH_USED = 'BRANCH_USED';
export const BRANCH_USED_NULL = 'BRANCH_USED_NULL';
export const UPDATE_BRANCH = 'UPDATE_BRANCH';

//TYPES DE ALERTAS
export const VIEW_ALERT = 'VIEW_ALERT';
export const HIDE_ALERT = 'HIDE_ALERT';